# Generated by Django 3.1.12 on 2025-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20250530_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_redact_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
