# Generated by Django 3.1.12 on 2025-05-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_myuser_last_redact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='last_redact_date',
        ),
    ]
