# Generated by Django 3.1.12 on 2025-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_myuser_last_redact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
