# Generated by Django 3.1.12 on 2025-05-30 17:45

from django.db import migrations
import djongo.models.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20250530_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AddField(
            model_name='myuser',
            name='comments',
            field=djongo.models.fields.ArrayField(default=list, model_container=user_profile.models.IntItem),
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='User',
        ),
    ]
