# Generated by Django 3.1.12 on 2025-05-30 22:04

import bread.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Composition', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Recipe', models.TextField()),
                ('Rate', models.FloatField()),
                ('Image', models.CharField(max_length=200)),
                ('CommentIDs', djongo.models.fields.ArrayField(default=list, model_container=bread.models.IntItem)),
            ],
        ),
    ]
