# Generated by Django 3.1.12 on 2025-04-20 23:13

import bread.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Text', models.TextField()),
                ('Rating', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('RecipeID', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Composition', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Recipe', models.TextField()),
                ('Rate', models.IntegerField()),
                ('CommentIDs', djongo.models.fields.ArrayField(default=list, model_container=bread.models.IntItem)),
            ],
            options={
                'db_table': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Nickname', models.CharField(max_length=100)),
                ('Create_Date', models.DateTimeField(auto_now_add=True)),
                ('Last_Redact_Date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('CommentIDs', djongo.models.fields.ArrayField(default=list, model_container=bread.models.IntItem)),
                ('hash_Password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
