# Generated by Django 3.1.12 on 2025-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Composition', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Recipe', models.TextField()),
                ('Rate', models.IntegerField()),
            ],
        ),
    ]
